### PR TITLE
welcome screen

### PR DESCRIPTION
**Pull request by Bhavani-078**

### CODE REVIEW

**Review by maheshalyana — APPROVED** [review]

**Review by Abhi-0987 — COMMENTED** [review]
image

Minor changes are needed.. moving it to development

**Review by maheshalyana — COMMENTED** [review]
remove that menu icon in top right corner, and give space between the text in bottom

**Comment by Bhavani-078** [comment]
> remove that menu icon in top right corner, and give space between the text in bottom

Ok anna

**Review by Abhi-0987 — COMMENTED** [review]
image
image

Screen matches with the design and test is also passed..!! moving it to acceptance

**Pull request merged**
